package tn.esprit.backend.entity;

import com.fasterxml.jackson.annotation.JsonBackReference;
import jakarta.persistence.*;
import lombok.*;

import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "quiz_attempt_answers")
@Getter @Setter @NoArgsConstructor @AllArgsConstructor @Builder
public class QuizAttemptAnswer {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "quiz_attempt_id", nullable = false)
    @JsonBackReference
    private QuizAttempt quizAttempt;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "question_id", nullable = false)
    private Question question;

    // For SINGLE_CHOICE
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "selected_choice_id")
    private Choice selectedChoice;

    // For MULTIPLE_CHOICE (ManyToMany relationship to Choices)
    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(
            name = "attempt_answer_choices",
            joinColumns = @JoinColumn(name = "attempt_answer_id"),
            inverseJoinColumns = @JoinColumn(name = "choice_id")
    )
    @Builder.Default
    private List<Choice> selectedChoices = new ArrayList<>();

    // For OPEN_ENDED questions
    @Column(columnDefinition = "TEXT")
    private String openEndedAnswer;

    // Feedback generated by Gemini after evaluating the openEndedAnswer
    @Column(columnDefinition = "TEXT")
    private String aiFeedback;

    @Column(nullable = false)
    private Boolean correct;
}