spring.application.name=backend

server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/mamaai-integration-1-7-3-6?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# JWT
app.jwt.secret=H7xPq9Lm2VfT4aZ8QwEr6YuN3KsJdR5Cb1XoGpL0tMiBnUvDhFeCyWzA8rS9kTq2
app.jwt.access-expiration-ms=9000000
app.jwt.refresh-expiration-ms=604800000


spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.default-property-inclusion=non_null

# AI integrations for module 7
ollama.base-url=http://localhost:11434
ollama.model=llama3.2
ollama.keep-alive=10m

gemini.base-url=https://generativelanguage.googleapis.com/v1beta
gemini.model=gemini-2.5-flash
gemini.api-key=AIzaSyDKk7Ev2wgU_2YndfWFobK-hrraG7jDvtQ
# gemini.api-key=${GEMINI_API_KEY:}

# Google OAuth2 - CORRECTION PRINCIPALE
spring.security.oauth2.client.registration.google.client-id=869922090743-oqqmkhkcmc6nmsdffmv9g87cqjpdp46m.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8081/login/oauth2/code/google

# Upload photos de profil
app.upload.dir=uploads/avatars
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
app.base-url=http://localhost:8081

# Mail SMTP Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tfakedni.contact@gmail.com
spring.mail.password=tcdr qncs bdex uyjv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Anthropic Claude API (Face ID verification)
gemini-youssef.api-key=AIzaSyCR2MnxGi0qzV4donM0XD19uoJ0WxUzOWE
# AIzaSyBst_-sz_Jl_YZbRXCfJNNTHXIWsC0zgwY
# AIzaSyCtqayTzKRfTTma27dtU402YIbn9a7z_Uc
# AIzaSyD2LKgJ8aNbaGFoiZnrRpDcTRN0ulVB1pA

#Ai
groq.api-key=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

anthropic.api.key=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

spring.task.scheduling.enabled=true

# Ikbel Application Properties
groq-ikbel.api.key=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

storytelling.audio.storage=uploads/storytelling-audio

elevenlabs.api.base-url=https://api.elevenlabs.io
elevenlabs.api.key=d2281b612ccbbe62d7144f3311bcffa519642951ca7b8e3f85e2cb0af0b477ca
elevenlabs.model.id=eleven_multilingual_v2

voice.analysis.base-url=http://localhost:8002

#yomna module 5
#Flask
ml.service.url=http://localhost:5000
# Async thread pool for ML analysis (used by AsyncConfig)
spring.task.execution.pool.core-size=2
spring.task.execution.pool.max-size=5
spring.task.execution.pool.queue-capacity=50
spring.task.execution.thread-name-prefix=ml-task-

# Twilio SMS
twilio.account-sid=ACdf5500f14293835788dfa1ff313acfc5
twilio.auth-token=a47c30ec15b076d0a49cc7efb2ab3fb5
twilio.from-number=+17406658961
groq-yomna.api.key=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
spring.cache.type=simple

spring.servlet.multipart.enabled=true

# Stripe
stripe.secret-key=sk_test_51Q8guRRqOXMp4o1HGPTVEZpvcogn1v8SxvtYbNT2ugbc5vYyG4d8wVGULXizAQe6xQnhlgeBQRg4KFRMi9kAvXLF00OyawA2RF
stripe.webhook-secret=sk_test_51Q8guRRqOXMp4o1HGPTVEZpvcogn1v8SxvtYbNT2ugbc5vYyG4d8wVGULXizAQe6xQnhlgeBQRg4KFRMi9kAvXLF00OyawA2RF
stripe.success-url=http://localhost:4200/shop/order-success
stripe.cancel-url=http://localhost:4200/shop/order-cancel
